if(EXISTS $ENV{has_pythia6})
  add_definitions(-DPYTHIA6)
endif()
if(EXISTS $ENV{has_grv})
  add_definitions(-DGRVPDF)
endif()

if($ENV{HOSTNAME} MATCHES "^lxplus[0-9]+.cern.ch")
  set(BASE_DIR "/cvmfs/sft.cern.ch/lcg/external")
  set(GSL_DIR "${BASE_DIR}/GSL/1.14/x86_64-slc5-gcc44-opt")
  set(HEPMC_DIR "${BASE_DIR}/HepMC/2.06.08/x86_64-slc6-gcc48-opt")

  message(STATUS "Compiling on LXPLUS. Do not forget to source the environment variables!")
  #--- searching for GSL
  find_library(GSL_LIB gsl HINTS "${GSL_DIR}/lib")
  find_library(GSL_CBLAS_LIB gslcblas HINTS "${GSL_DIR}/lib")
  #--- searching for HepMC
  find_library(HEPMC_LIB HepMC HINTS "${HEPMC_DIR}/lib")
  find_library(HEPMC_FIO_LIB HepMCfio HINTS "${HEPMC_DIR}/lib")
  find_path(HEPMC_INCLUDE HepMC HINTS "${HEPMC_DIR}/include")
  find_library(LIBCONFIG config++)
  find_library(MUPARSER muparser)
else()
  find_library(GSL_LIB gsl)
  find_library(GSL_CBLAS_LIB gslcblas)
  find_library(HEPMC_LIB HepMC)
  find_path(HEPMC_INCLUDE HepMC)
  find_library(LIBCONFIG config++)
  find_library(MUPARSER muparser)
endif()

if(GSL_LIB)
  message(STATUS "GSL found in ${GSL_LIB}")
  list(APPEND CEPGEN_EXTERNAL_REQS ${GSL_LIB} ${GSL_CBLAS_LIB})
else()
  message(FATAL_ERROR "GSL not found on your system!")
endif()
if(LHAPDF)
  message(STATUS "LHAPDF found in ${LHAPDF}")
  list(APPEND CEPGEN_EXTERNAL_REQS ${LHAPDF})
  add_definitions(-DLIBLHAPDF)
  include_directories(${LHAPDF_INCLUDE})
endif()
if(HEPMC_LIB)
  message(STATUS "HepMC found in ${HEPMC_INCLUDE}")
  list(APPEND CEPGEN_EXTERNAL_REQS ${HEPMC_LIB})
  if(HEPMC_FIO_LIB)
    list(APPEND CEPGEN_EXTERNAL_REQS ${HEPMC_FIO_LIB})
  endif()
  add_definitions(-DLIBHEPMC)
  include_directories(${HEPMC_INCLUDE})
endif()
if(LIBCONFIG)
  message(STATUS "libconfig++ found in ${LIBCONFIG}")
  add_definitions(-DLIBCONFIG)
  list(APPEND CEPGEN_EXTERNAL_REQS ${LIBCONFIG})
endif()
if(MUPARSER)
  message(STATUS "muParser found in ${MUPARSER}")
  add_definitions(-DMUPARSER)
  list(APPEND CEPGEN_EXTERNAL_REQS ${MUPARSER})
endif()
